### ISSUE TITLE
Failing for non master branches

### ISSUE THREAD

**Issue by aalemayhu** [vitalyliber/dokku-github-action#20]
Hei there 👋🏾 

Love this action. It mostly works fine, but when I use for a dev branch it fails a lot. Do you have any ideas why? Thanks 🙏🏾

Here is also the latest failure https://github.com/alemayhu/notion2anki/actions/runs/251606558

Below is the configuration I use

```
name: Deploy to dev.2anki.net

on:
  push:
    branches:
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Dokku deploy
      uses: vitalyliber/dokku-github-action@v4.0
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        HOST: 2anki.net
        PROJECT: dev.notion
```
